export const MainStackScreenNames = {
  MapScreen: 'MapScreen',
  DriverProfile: 'DriverProfile',
  FoundDriver: 'FoundDriver',
  MainScreen: 'MainScreen',
  LoginScreen: 'LoginScreen',
  FisrtSignUpScreen: 'FisrtSignUpScreen',
  SecondSignUpScreen: 'SecondSignUpScreen',
  ThirdSignUpScreen: 'ThirdSignUpScreen',
  SuccessSignUpScreen: 'SuccessSignUpScreen',
  CheckoutScreen: 'CheckoutScreen',
  ProfileScreen: 'ProfileScreen',
  HelpScreen: 'HelpScreen',
  PaymentScreen: 'PaymentScreen',
  ListingPetsScreen: 'ListingPetsScreen',
  MessagesScreen: 'MessagesScreen',
  PaymentDescriptionScreen: 'PaymentDescriptionScreen',
  ConfigScreen: 'ConfigScreen',
  InitialAddPetScreen: 'InitialAddPetScreen',
  UserTravelsScreen: 'UserTravelsScreen',
  RaceDetailsScreen: 'RaceDetailsScreen',
  PartnerDriverScreen: 'PartnerDriverScreen',
  TermsAndPrivacyScreen: 'TermsAndPrivacyScreen',
  PaymentDescriptionQuest1Screen: 'PaymentDescriptionQuest1Screen',
  PartnerDriverQuest1Screen: 'PartnerDriverQuest1Screen',
  PaymentDescriptionQuest2Screen: 'PaymentDescriptionQuest2Screen',
  PaymentDescriptionQuest3Screen: 'PaymentDescriptionQuest3Screen',
  PaymentDescriptionQuest4Screen: 'PaymentDescriptionQuest4Screen',
  RaceDetailsQuest1Screen: 'RaceDetailsQuest1Screen',
  RaceDetailsQuest2Screen: 'RaceDetailsQuest2Screen',
  RaceDetailsQuest3Screen: 'RaceDetailsQuest3Screen',
  RaceDetailsQuest4Screen: 'RaceDetailsQuest4Screen',
  RaceDetailsQuest5Screen: 'RaceDetailsQuest5Screen',
  RaceDetailsQuest6Screen: 'RaceDetailsQuest6Screen',



}
