export const MainStackScreenNames = {
  MapScreen: 'MapScreen',
  DriverProfile: 'DriverProfile',
  FoundDriver: 'FoundDriver',
  MainScreen: 'MainScreen',
  LoginScreen: 'LoginScreen',
  FisrtSignUpScreen: 'FisrtSignUpScreen',
  SecondSignUpScreen: 'SecondSignUpScreen',
  ThirdSignUpScreen: 'ThirdSignUpScreen',
  SuccessSignUpScreen: 'SuccessSignUpScreen',
  CheckoutScreen: 'CheckoutScreen',
  ProfileScreen: 'ProfileScreen',
  HelpScreen: 'HelpScreen',
  PaymentScreen: 'PaymentScreen',
  ListingPetsScreen: 'ListingPetsScreen',
  MessagesScreen: 'MessagesScreen',
  PaymentDescriptionScreen: 'PaymentDescriptionScreen',
  ConfigScreen: 'ConfigScreen',
  InitialAddPetScreen: 'InitialAddPetScreen',
  UserTravelsScreen: 'UserTravelsScreen',
}
